spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: notification-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
    discovery:
      enabled: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  mail:
    host: smtp.ethereal.email
    port: 587
    username: meggie.lebsack22@ethereal.email
    password: kcRSFffcJfhQeQpan7
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
